import { COOKIES, CURRENT_TERMS_VERSION, ROUTES, TRIAL_DAYS } from '@ilm/contracts';
import { FastifyAdapter, type NestFastifyApplication } from '@nestjs/platform-fastify';
import { Test } from '@nestjs/testing';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { AppModule } from '../app.module';
import { createAdminClient, type PrismaClient } from '../prisma';
import { PasswordService } from '../shared/auth/password.service';
import { MAIL } from '../shared/mail/mail.port';

import { RecordingMailer, runSignupFlow } from './signup-flow';

/**
 * Sign in with email and password alone (ADR-0009), and self-serve signup
 * (ADR-0010).
 *
 * The property under test is not "does the happy path work" â€” it is that **the
 * apex discloses nothing about which schools exist until a password has been
 * verified**. That is the rule the old "type your school's short name" field
 * was protecting, and removing the field must not have removed the rule.
 *
 * The fixture is two schools that share one email address with the same
 * password, which is the case that makes global sign-in hard: a parent with
 * children at two schools, or a teacher at two campuses. `UNIQUE(school_id,
 * email)` permits it by design (docs/07 Â§2).
 */

const SCHOOL_ONE = '33333333-3333-4333-8333-333333333341';
const SCHOOL_TWO = '33333333-3333-4333-8333-333333333342';
const USER_ONE = '44444444-4444-4444-8444-444444444451';
const USER_TWO = '44444444-4444-4444-8444-444444444452';
const USER_SOLO = '44444444-4444-4444-8444-444444444453';

const HOST_ONE = 'shared-one-e2e.localhost';
/** No school in the address. This is the apex, and the point of these tests. */
const APEX = 'localhost';

const SHARED_EMAIL = 'parent@two-schools-e2e.test';
const SOLO_EMAIL = 'head@shared-one-e2e.test';
const PASSWORD = 'correct-horse-battery-staple';

/** A slug no fixture claims, so the signup test can create it and clean it up. */
const NEW_SLUG = 'signup-e2e-school';

let app: NestFastifyApplication;
let admin: PrismaClient;
let mailer: RecordingMailer;

const SCHOOL_IDS = [SCHOOL_ONE, SCHOOL_TWO];

async function wipe(): Promise<void> {
  // Order matters: children before parents, and the signed-up school is found
  // by slug because its id is generated by the endpoint under test.
  const createdBySignup = await admin.$queryRaw<{ id: string }[]>`
    SELECT id FROM schools WHERE slug = ${NEW_SLUG}
  `;
  const ids = [...SCHOOL_IDS, ...createdBySignup.map((row) => row.id)];

  for (const table of [
    'auth_handoffs',
    'school_agreements',
    'sessions',
    'audit_logs',
    'user_roles',
    'users',
  ]) {
    await admin.$executeRawUnsafe(`DELETE FROM "${table}" WHERE school_id = ANY($1::uuid[])`, ids);
  }
  await admin.$executeRawUnsafe(`DELETE FROM schools WHERE id = ANY($1::uuid[])`, ids);
  await admin.$executeRaw`DELETE FROM signup_intents WHERE email LIKE '%signup-e2e%' OR email LIKE '%two-schools-e2e%' OR email LIKE '%shared-one-e2e%'`;
}

beforeAll(async () => {
  process.env['APP_DOMAIN'] = 'localhost';

  admin = createAdminClient({ url: process.env['DATABASE_ADMIN_URL'] ?? '' });
  await wipe();

  await admin.$executeRaw`
    INSERT INTO schools (id, name, slug, created_at, updated_at) VALUES
      (${SCHOOL_ONE}::uuid, 'Shared One', 'shared-one-e2e', now(), now()),
      (${SCHOOL_TWO}::uuid, 'Shared Two', 'shared-two-e2e', now(), now())
  `;

  const hash = await new PasswordService().hash(PASSWORD);

  await admin.$executeRaw`
    INSERT INTO users (id, school_id, email, name, password_hash, status, created_at, updated_at)
    VALUES
      (${USER_ONE}::uuid, ${SCHOOL_ONE}::uuid, ${SHARED_EMAIL}, 'Parent at One', ${hash}, 'ACTIVE', now(), now()),
      (${USER_TWO}::uuid, ${SCHOOL_TWO}::uuid, ${SHARED_EMAIL}, 'Parent at Two', ${hash}, 'ACTIVE', now(), now()),
      (${USER_SOLO}::uuid, ${SCHOOL_ONE}::uuid, ${SOLO_EMAIL}, 'Head of One', ${hash}, 'ACTIVE', now(), now())
  `;

  await admin.$executeRaw`
    INSERT INTO user_roles (id, school_id, user_id, role, created_at) VALUES
      (gen_random_uuid(), ${SCHOOL_ONE}::uuid, ${USER_ONE}::uuid, 'PARENT', now()),
      (gen_random_uuid(), ${SCHOOL_TWO}::uuid, ${USER_TWO}::uuid, 'PARENT', now()),
      (gen_random_uuid(), ${SCHOOL_ONE}::uuid, ${USER_SOLO}::uuid, 'OWNER', now())
  `;

  const moduleRef = await Test.createTestingModule({ imports: [AppModule] })
    .overrideProvider(MAIL)
    .useValue((mailer = new RecordingMailer()))
    .compile();
  app = moduleRef.createNestApplication<NestFastifyApplication>(new FastifyAdapter());

  const { default: cookie } = await import('@fastify/cookie');
  await app.register(cookie);
  await app.init();
  await app.getHttpAdapter().getInstance().ready();
}, 60_000);

afterAll(async () => {
  await app?.close();
  await wipe();
  await admin.$disconnect();
});

interface Choice {
  schoolId: string;
  name: string;
  slug: string;
  continueUrl: string;
}

async function signInAtApex(
  identifier: string,
  password: string,
): Promise<{ status: number; choices: Choice[]; detail?: string }> {
  const response = await app.inject({
    method: 'POST',
    url: ROUTES.auth.login,
    headers: { host: APEX },
    payload: { identifier, password },
  });

  if (response.statusCode >= 400) {
    return {
      status: response.statusCode,
      choices: [],
      detail: response.json<{ detail: string }>().detail,
    };
  }

  const body = response.json<{ data: { kind: string; choices: Choice[] } }>();
  return { status: response.statusCode, choices: body.data.choices };
}

/** Pull the `?t=` value out of a continue URL, the way a browser would. */
function tokenFrom(continueUrl: string): string {
  return new URL(continueUrl).searchParams.get('t') ?? '';
}

describe('signing in with no school in the address', () => {
  it('finds the one school an address belongs to', async () => {
    const { status, choices } = await signInAtApex(SOLO_EMAIL, PASSWORD);

    expect(status).toBe(201);
    expect(choices).toHaveLength(1);
    expect(choices[0]?.slug).toBe('shared-one-e2e');
    // The URL must point at the school's own hostname. Signing in at the apex
    // and staying there is exactly what host-only cookies make impossible.
    expect(choices[0]?.continueUrl).toContain('shared-one-e2e.localhost');
  });

  it('sets no cookies at the apex', async () => {
    // The apex cannot issue a session: the cookie would be for the wrong host.
    // If this ever starts setting one, COOKIE_DOMAIN has been widened and every
    // tenant now shares a cookie.
    const response = await app.inject({
      method: 'POST',
      url: ROUTES.auth.login,
      headers: { host: APEX },
      payload: { identifier: SOLO_EMAIL, password: PASSWORD },
    });

    expect(response.statusCode).toBe(201);
    expect(response.headers['set-cookie']).toBeUndefined();
  });

  it('offers every school the password unlocked, and only those', async () => {
    const { choices } = await signInAtApex(SHARED_EMAIL, PASSWORD);

    expect(choices).toHaveLength(2);
    expect(choices.map((choice) => choice.slug).sort()).toEqual([
      'shared-one-e2e',
      'shared-two-e2e',
    ]);
  });

  it('says nothing about which schools exist when the password is wrong', async () => {
    // Three identifiers: registered at two schools, registered at one, and
    // registered nowhere. All three must be indistinguishable.
    const atTwo = await signInAtApex(SHARED_EMAIL, 'not-the-password');
    const atOne = await signInAtApex(SOLO_EMAIL, 'not-the-password');
    const nowhere = await signInAtApex('stranger@nowhere-e2e.test', 'not-the-password');

    expect(atTwo.status).toBe(401);
    expect(atOne.status).toBe(atTwo.status);
    expect(nowhere.status).toBe(atTwo.status);
    expect(atOne.detail).toBe(atTwo.detail);
    expect(nowhere.detail).toBe(atTwo.detail);
  });
});

describe('the handoff', () => {
  it('exchanges a token for a session on the schoolâ€™s own host', async () => {
    const { choices } = await signInAtApex(SOLO_EMAIL, PASSWORD);
    const token = tokenFrom(choices[0]?.continueUrl ?? '');

    const response = await app.inject({
      method: 'POST',
      url: ROUTES.auth.continue,
      headers: { host: HOST_ONE },
      payload: { token },
    });

    expect(response.statusCode).toBe(201);

    const raw = response.headers['set-cookie'];
    const list = Array.isArray(raw) ? raw : [String(raw)];
    expect(list.some((entry) => entry.startsWith(COOKIES.accessToken))).toBe(true);
    expect(list.every((entry) => entry.includes('HttpOnly'))).toBe(true);

    expect(response.json<{ data: { school: { slug: string } } }>().data.school.slug).toBe(
      'shared-one-e2e',
    );
  });

  it('cannot be redeemed twice', async () => {
    // Single use is the whole reason this is a table row rather than a
    // self-contained signed token. A replay inside the two-minute window would
    // otherwise be a second session from one password.
    const { choices } = await signInAtApex(SOLO_EMAIL, PASSWORD);
    const token = tokenFrom(choices[0]?.continueUrl ?? '');

    const first = await app.inject({
      method: 'POST',
      url: ROUTES.auth.continue,
      headers: { host: HOST_ONE },
      payload: { token },
    });
    const second = await app.inject({
      method: 'POST',
      url: ROUTES.auth.continue,
      headers: { host: HOST_ONE },
      payload: { token },
    });

    expect(first.statusCode).toBe(201);
    expect(second.statusCode).toBe(401);
  });

  it('cannot be redeemed at another schoolâ€™s address', async () => {
    // The school comes from the request host and is matched against the row, so
    // this endpoint is not a way to pick a tenant.
    const { choices } = await signInAtApex(SHARED_EMAIL, PASSWORD);
    const forSchoolOne = choices.find((choice) => choice.slug === 'shared-one-e2e');
    const token = tokenFrom(forSchoolOne?.continueUrl ?? '');

    const response = await app.inject({
      method: 'POST',
      url: ROUTES.auth.continue,
      headers: { host: 'shared-two-e2e.localhost' },
      payload: { token },
    });

    expect(response.statusCode).toBe(401);
  });

  it('is refused at the apex, where there is no school to redeem it against', async () => {
    const { choices } = await signInAtApex(SOLO_EMAIL, PASSWORD);
    const token = tokenFrom(choices[0]?.continueUrl ?? '');

    const response = await app.inject({
      method: 'POST',
      url: ROUTES.auth.continue,
      headers: { host: APEX },
      payload: { token },
    });

    expect(response.statusCode).toBe(401);
  });

  it('rejects a made-up token', async () => {
    const response = await app.inject({
      method: 'POST',
      url: ROUTES.auth.continue,
      headers: { host: HOST_ONE },
      payload: { token: 'not-a-real-handoff-token' },
    });

    expect(response.statusCode).toBe(401);
  });
});


describe('self-serve signup', () => {
  const flow = {
    name: 'Founder',
    email: 'founder@signup-e2e.test',
    password: 'a-long-enough-passphrase',
    school: {
      name: 'Signup E2E School',
      slug: NEW_SLUG,
      city: 'Lahore',
      phone: '+923001234567',
      email: 'office@signup-e2e.test',
    },
  };

  it('creates the school after credentials, OTP and school details', async () => {
    const response = await runSignupFlow(app, mailer, flow, APEX);

    expect(response.statusCode).toBe(201);

    const body = response.json<{
      data: { school: { id: string; slug: string }; trialEndsAt: string; continueTo: Choice };
    }>().data;

    expect(body.school.slug).toBe(NEW_SLUG);
    expect(body.continueTo.continueUrl).toContain(`${NEW_SLUG}.localhost`);

    const daysAway = (new Date(body.trialEndsAt).getTime() - Date.now()) / (24 * 60 * 60 * 1000);
    expect(daysAway).toBeLessThanOrEqual(TRIAL_DAYS);
    expect(daysAway).toBeGreaterThan(TRIAL_DAYS - 0.01);

    const school = await admin.$queryRaw<{ status: string; trial_ends_at: Date | null }[]>`
      SELECT status::text, trial_ends_at FROM schools WHERE id = ${body.school.id}::uuid
    `;
    expect(school[0]?.status).toBe('TRIAL');
    expect(school[0]?.trial_ends_at).not.toBeNull();

    const roles = await admin.$queryRaw<{ role: string }[]>`
      SELECT role::text FROM user_roles WHERE school_id = ${body.school.id}::uuid
    `;
    expect(roles.map((row) => row.role)).toEqual(['OWNER']);

    const agreements = await admin.$queryRaw<{ version: string; accepted_by_email: string }[]>`
      SELECT version, accepted_by_email FROM school_agreements
      WHERE school_id = ${body.school.id}::uuid
    `;
    expect(agreements).toHaveLength(1);
    expect(agreements[0]?.version).toBe(CURRENT_TERMS_VERSION);
    expect(agreements[0]?.accepted_by_email).toBe(flow.email);

    const users = await admin.$queryRaw<{ email_verified_at: Date | null }[]>`
      SELECT email_verified_at FROM users WHERE school_id = ${body.school.id}::uuid
    `;
    expect(users[0]?.email_verified_at).not.toBeNull();
  });

  it('signs the new owner in through the same handoff', async () => {
    const created = await admin.$queryRaw<{ id: string }[]>`
      SELECT id FROM schools WHERE slug = ${NEW_SLUG}
    `;
    expect(created).toHaveLength(1);

    const { choices } = await signInAtApex(flow.email, flow.password);
    expect(choices).toHaveLength(1);

    const response = await app.inject({
      method: 'POST',
      url: ROUTES.auth.continue,
      headers: { host: `${NEW_SLUG}.localhost` },
      payload: { token: tokenFrom(choices[0]?.continueUrl ?? '') },
    });

    expect(response.statusCode).toBe(201);
    expect(response.json<{ data: { mustChangePassword: boolean } }>().data.mustChangePassword).toBe(
      false,
    );
  });

  it('refuses a slug another school already holds', async () => {
    const response = await runSignupFlow(
      app,
      mailer,
      { ...flow, email: 'other@signup-e2e.test', school: { ...flow.school } },
      APEX,
    );

    expect(response.statusCode).toBe(409);
  });

  it('refuses a reserved slug', async () => {
    const response = await runSignupFlow(
      app,
      mailer,
      {
        name: 'Nobody',
        email: 'reserved@signup-e2e.test',
        password: flow.password,
        school: {
          name: 'Nope',
          slug: 'api',
          city: 'Lahore',
          phone: '+923001234567',
          email: 'office@reserved-signup.test',
        },
      },
      APEX,
    );

    expect(response.statusCode).toBeGreaterThanOrEqual(400);
  });

  it('refuses to start without accepted terms', async () => {
    const response = await app.inject({
      method: 'POST',
      url: ROUTES.public.signupStart,
      headers: { host: APEX },
      payload: {
        name: 'Founder',
        email: 'terms@signup-e2e.test',
        password: flow.password,
        confirmPassword: flow.password,
        acceptedTerms: false,
        termsVersion: CURRENT_TERMS_VERSION,
      },
    });

    expect(response.statusCode).toBe(400);
  });

  it('answers slug availability without revealing anything else', async () => {
    const taken = await app.inject({
      method: 'GET',
      url: `${ROUTES.public.slugAvailable}?slug=${NEW_SLUG}`,
      headers: { host: APEX },
    });
    const free = await app.inject({
      method: 'GET',
      url: `${ROUTES.public.slugAvailable}?slug=definitely-not-taken-e2e`,
      headers: { host: APEX },
    });
    const reserved = await app.inject({
      method: 'GET',
      url: `${ROUTES.public.slugAvailable}?slug=admin`,
      headers: { host: APEX },
    });

    expect(taken.json<{ data: { available: boolean; reason?: string } }>().data).toEqual({
      slug: NEW_SLUG,
      available: false,
      reason: 'taken',
    });
    expect(free.json<{ data: { available: boolean } }>().data.available).toBe(true);
    expect(reserved.json<{ data: { reason?: string } }>().data.reason).toBe('reserved');
    expect(taken.body).not.toContain('Signup E2E School');
  });
});
